services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.dockerfile
    ports:
      - "8055:8055"
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    restart: always

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.dockerfile
    ports:
      - "5557:5557"
    volumes:
      - ./frontend:/app
    working_dir: /app
    restart: always
